{% set version = "1.0.6" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-textrecipes
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/textrecipes_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/textrecipes/textrecipes_{{ version }}.tar.gz
  sha256: 3b12e01d622311610674e2ae7c1b6f2007c9f19665d64046a0dc728537299430

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  skip: true  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-cpp11                      # [build_platform != target_platform]
    - r-dplyr                      # [build_platform != target_platform]
    - r-generics                   # [build_platform != target_platform]
    - r-glue                       # [build_platform != target_platform]
    - r-lifecycle                  # [build_platform != target_platform]
    - r-magrittr                   # [build_platform != target_platform]
    - r-matrix                     # [build_platform != target_platform]
    - r-purrr                      # [build_platform != target_platform]
    - r-recipes                    # [build_platform != target_platform]
    - r-rlang                      # [build_platform != target_platform]
    - r-snowballc                  # [build_platform != target_platform]
    - r-tibble                     # [build_platform != target_platform]
    - r-tokenizers                 # [build_platform != target_platform]
    - r-vctrs                      # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-cpp11
    - r-dplyr
    - r-generics >=0.1.0
    - r-glue
    - r-lifecycle
    - r-magrittr
    - r-matrix
    - r-purrr
    - r-recipes >=1.0.7
    - r-rlang
    - r-snowballc
    - r-tibble
    - r-tokenizers
    - r-vctrs
  run:
    - r-base
    - r-cpp11
    - r-dplyr
    - r-generics >=0.1.0
    - r-glue
    - r-lifecycle
    - r-magrittr
    - r-matrix
    - r-purrr
    - r-recipes >=1.0.7
    - r-rlang
    - r-snowballc
    - r-tibble
    - r-tokenizers
    - r-vctrs
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('textrecipes')"           # [not win]
    - "\"%R%\" -e \"library('textrecipes')\""  # [win]

about:
  home: https://textrecipes.tidymodels.org/
  dev_url: https://github.com/tidymodels/textrecipes
  license: MIT
  summary: Converting text to numerical features requires specifically created procedures, which are implemented as steps according to the 'recipes' package. These steps allows for tokenization, filtering, counting (tf and tfidf) and feature hashing.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor
